//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.1
//     from Assets/_Scripts/Input/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""Map"",
            ""id"": ""cf4c5245-3c79-42ab-8f45-2ac8d36d5d41"",
            ""actions"": [
                {
                    ""name"": ""East"",
                    ""type"": ""Button"",
                    ""id"": ""d4ca2e65-abad-448f-8693-99a8cfa42b7b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""North"",
                    ""type"": ""Button"",
                    ""id"": ""e64fd236-e143-4ab7-9dff-14c484097965"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""South"",
                    ""type"": ""Button"",
                    ""id"": ""a1a78ab2-f50f-493d-99fa-2281f2443e3b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""West"",
                    ""type"": ""Button"",
                    ""id"": ""c9a89031-3300-469f-b2b0-8bd28ff34418"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DUp"",
                    ""type"": ""Button"",
                    ""id"": ""aff58bf9-f94b-4e3b-a8e1-fbaf8499557f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DRight"",
                    ""type"": ""Button"",
                    ""id"": ""add395cf-7bdf-46c8-87dc-d7fba50175b0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DDown"",
                    ""type"": ""Button"",
                    ""id"": ""7a81c679-cc20-4a6b-beb7-e42a175cca92"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DLeft"",
                    ""type"": ""Button"",
                    ""id"": ""387687b7-4a75-4fc4-b0b8-56c364721eed"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""L1"",
                    ""type"": ""Button"",
                    ""id"": ""ee950ba4-7e31-4b16-9977-1c96fc9f4bfa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""L2"",
                    ""type"": ""Button"",
                    ""id"": ""90667909-de5c-4b37-95c5-9f50d01bd4e3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""L3"",
                    ""type"": ""Button"",
                    ""id"": ""1ee2f25b-f79d-4594-b735-17ebb69f723a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""R1"",
                    ""type"": ""Button"",
                    ""id"": ""e2db57f5-e3ce-480b-a149-a56f35c19116"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""R2"",
                    ""type"": ""Button"",
                    ""id"": ""dc396875-3d15-4360-a2f4-dd28e21ac4ea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""R3"",
                    ""type"": ""Button"",
                    ""id"": ""3a7ac041-37c7-48df-ba84-a4d7c7989442"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Start"",
                    ""type"": ""Button"",
                    ""id"": ""2c00b600-abcb-40d3-8d45-c6156daecbea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""592e4435-ba9c-489c-9059-ce281b0b7404"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LStick"",
                    ""type"": ""Value"",
                    ""id"": ""6de630db-3f66-4059-a1a0-8184b6f3b451"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RStick"",
                    ""type"": ""Value"",
                    ""id"": ""2668fc9f-83b2-4429-b3f4-b5e93f13ca76"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RStickAltX"",
                    ""type"": ""Value"",
                    ""id"": ""fd7078e1-177d-4a43-83d4-b0ee1990ba14"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RStickAltY"",
                    ""type"": ""Value"",
                    ""id"": ""5c1e9578-023b-4e98-a67f-90126b87c9fd"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0bc9be06-d74b-4a3a-a12c-43e841a10182"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""East"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""adf75bfd-bec5-4bcc-8b1a-160add60ce0f"",
                    ""path"": ""<HID::Unknown 8BitDo N30 Pro 2>/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""East"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e29fc532-dd18-454d-b91c-17e303b2353f"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""East"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8cc804f4-4ad5-49ce-aab3-9530bc3b45fb"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""North"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""db8871de-1341-4420-8f34-f834f170e8c0"",
                    ""path"": ""<HID::Unknown 8BitDo N30 Pro 2>/button4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""North"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""30928c77-4aba-481e-bc62-dd074e6bd971"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""South"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1cc7ecb2-cb2e-47bb-9fb6-ed5f791ecc47"",
                    ""path"": ""<HID::Unknown 8BitDo N30 Pro 2>/button2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""South"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7b2b101b-dc1e-4a25-83dc-76beb9a77c1a"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""West"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""74e8fc48-d053-4066-a92f-62540c4f736b"",
                    ""path"": ""<HID::Unknown 8BitDo N30 Pro 2>/button5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""West"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""45d1920f-9e93-47ee-a93d-da27bb5d1cf6"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""045616c1-6bb1-4aac-83f1-421c69c11b8d"",
                    ""path"": ""<HID::Unknown 8BitDo N30 Pro 2>/hat/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""91268288-eeaa-4be3-a308-bc6abe998ee3"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""90101f33-1b0d-4b08-80a8-339c47ae6e13"",
                    ""path"": ""<HID::Unknown 8BitDo N30 Pro 2>/hat/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""526c6652-243b-4073-a6a5-4b873f5b48bc"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ed7ab7c3-f136-4d54-8c33-5aa951b5c04e"",
                    ""path"": ""<HID::Unknown 8BitDo N30 Pro 2>/hat/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""334fa838-3883-45bb-a4c0-b1c18bad5b65"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3d0ba40a-e273-4a2e-8dff-c8343823009d"",
                    ""path"": ""<HID::Unknown 8BitDo N30 Pro 2>/hat/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ad833532-eeb8-437a-b2ba-f5c14112f686"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""L1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""69ee8152-626e-491c-8f86-9929a8d87aa6"",
                    ""path"": ""<HID::Unknown 8BitDo N30 Pro 2>/button7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""L1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eb2af57f-9b09-446f-bc88-fda9a975a9be"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""L2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5dff0bbe-e224-4512-8653-510352963886"",
                    ""path"": ""<HID::Unknown 8BitDo N30 Pro 2>/button9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""L2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0647a4ed-d00b-4d02-865e-7941606365fd"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""L3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d667eae7-0c89-42a1-b053-398de690ff9c"",
                    ""path"": ""<HID::Unknown 8BitDo N30 Pro 2>/button14"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""L3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""641b779b-5bb5-422a-afa1-16fb8be3fbec"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""R1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b3e36cf1-e32a-4b42-af2f-192a277aac57"",
                    ""path"": ""<HID::Unknown 8BitDo N30 Pro 2>/button8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""R1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2548464-3198-4835-8591-ffaa15e5ea0e"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""R2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2a82ecd7-398b-4e6d-a320-bc281f2c8bc1"",
                    ""path"": ""<HID::Unknown 8BitDo N30 Pro 2>/button10"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""R2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f4793f5-f100-4bbc-9348-96cbb4dd2dc8"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""R3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""01eee8d5-3973-4411-8221-3897aae8a4b5"",
                    ""path"": ""<HID::Unknown 8BitDo N30 Pro 2>/button15"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""R3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ca9b6820-69a9-4ebf-8abb-5ac1b877f825"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0a070966-25ac-44e8-b08f-e8c78fbc3215"",
                    ""path"": ""<HID::Unknown 8BitDo N30 Pro 2>/button12"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""643c320c-1ef0-40bd-880f-a7023acce5ee"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9115a22d-92a5-4355-b23d-a9211d863917"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f8e3d99-36c9-4052-b223-859a4266c3a6"",
                    ""path"": ""<Joystick>/stick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fe605c0b-372b-4bf2-939e-c95eaf0bb77d"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1ba057ba-39d2-420d-97de-a35a5412dbc5"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2afbd30f-39b6-4b9c-9ec3-d7b17f5e47dd"",
                    ""path"": ""<HID::Unknown 8BitDo N30 Pro 2>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RStickAltX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""87e24a79-9ef9-41a6-a6a1-cd8d7023821e"",
                    ""path"": ""<HID::Unknown 8BitDo N30 Pro 2>/rz"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RStickAltY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Map
        m_Map = asset.FindActionMap("Map", throwIfNotFound: true);
        m_Map_East = m_Map.FindAction("East", throwIfNotFound: true);
        m_Map_North = m_Map.FindAction("North", throwIfNotFound: true);
        m_Map_South = m_Map.FindAction("South", throwIfNotFound: true);
        m_Map_West = m_Map.FindAction("West", throwIfNotFound: true);
        m_Map_DUp = m_Map.FindAction("DUp", throwIfNotFound: true);
        m_Map_DRight = m_Map.FindAction("DRight", throwIfNotFound: true);
        m_Map_DDown = m_Map.FindAction("DDown", throwIfNotFound: true);
        m_Map_DLeft = m_Map.FindAction("DLeft", throwIfNotFound: true);
        m_Map_L1 = m_Map.FindAction("L1", throwIfNotFound: true);
        m_Map_L2 = m_Map.FindAction("L2", throwIfNotFound: true);
        m_Map_L3 = m_Map.FindAction("L3", throwIfNotFound: true);
        m_Map_R1 = m_Map.FindAction("R1", throwIfNotFound: true);
        m_Map_R2 = m_Map.FindAction("R2", throwIfNotFound: true);
        m_Map_R3 = m_Map.FindAction("R3", throwIfNotFound: true);
        m_Map_Start = m_Map.FindAction("Start", throwIfNotFound: true);
        m_Map_Select = m_Map.FindAction("Select", throwIfNotFound: true);
        m_Map_LStick = m_Map.FindAction("LStick", throwIfNotFound: true);
        m_Map_RStick = m_Map.FindAction("RStick", throwIfNotFound: true);
        m_Map_RStickAltX = m_Map.FindAction("RStickAltX", throwIfNotFound: true);
        m_Map_RStickAltY = m_Map.FindAction("RStickAltY", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Map
    private readonly InputActionMap m_Map;
    private List<IMapActions> m_MapActionsCallbackInterfaces = new List<IMapActions>();
    private readonly InputAction m_Map_East;
    private readonly InputAction m_Map_North;
    private readonly InputAction m_Map_South;
    private readonly InputAction m_Map_West;
    private readonly InputAction m_Map_DUp;
    private readonly InputAction m_Map_DRight;
    private readonly InputAction m_Map_DDown;
    private readonly InputAction m_Map_DLeft;
    private readonly InputAction m_Map_L1;
    private readonly InputAction m_Map_L2;
    private readonly InputAction m_Map_L3;
    private readonly InputAction m_Map_R1;
    private readonly InputAction m_Map_R2;
    private readonly InputAction m_Map_R3;
    private readonly InputAction m_Map_Start;
    private readonly InputAction m_Map_Select;
    private readonly InputAction m_Map_LStick;
    private readonly InputAction m_Map_RStick;
    private readonly InputAction m_Map_RStickAltX;
    private readonly InputAction m_Map_RStickAltY;
    public struct MapActions
    {
        private @InputActions m_Wrapper;
        public MapActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @East => m_Wrapper.m_Map_East;
        public InputAction @North => m_Wrapper.m_Map_North;
        public InputAction @South => m_Wrapper.m_Map_South;
        public InputAction @West => m_Wrapper.m_Map_West;
        public InputAction @DUp => m_Wrapper.m_Map_DUp;
        public InputAction @DRight => m_Wrapper.m_Map_DRight;
        public InputAction @DDown => m_Wrapper.m_Map_DDown;
        public InputAction @DLeft => m_Wrapper.m_Map_DLeft;
        public InputAction @L1 => m_Wrapper.m_Map_L1;
        public InputAction @L2 => m_Wrapper.m_Map_L2;
        public InputAction @L3 => m_Wrapper.m_Map_L3;
        public InputAction @R1 => m_Wrapper.m_Map_R1;
        public InputAction @R2 => m_Wrapper.m_Map_R2;
        public InputAction @R3 => m_Wrapper.m_Map_R3;
        public InputAction @Start => m_Wrapper.m_Map_Start;
        public InputAction @Select => m_Wrapper.m_Map_Select;
        public InputAction @LStick => m_Wrapper.m_Map_LStick;
        public InputAction @RStick => m_Wrapper.m_Map_RStick;
        public InputAction @RStickAltX => m_Wrapper.m_Map_RStickAltX;
        public InputAction @RStickAltY => m_Wrapper.m_Map_RStickAltY;
        public InputActionMap Get() { return m_Wrapper.m_Map; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MapActions set) { return set.Get(); }
        public void AddCallbacks(IMapActions instance)
        {
            if (instance == null || m_Wrapper.m_MapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MapActionsCallbackInterfaces.Add(instance);
            @East.started += instance.OnEast;
            @East.performed += instance.OnEast;
            @East.canceled += instance.OnEast;
            @North.started += instance.OnNorth;
            @North.performed += instance.OnNorth;
            @North.canceled += instance.OnNorth;
            @South.started += instance.OnSouth;
            @South.performed += instance.OnSouth;
            @South.canceled += instance.OnSouth;
            @West.started += instance.OnWest;
            @West.performed += instance.OnWest;
            @West.canceled += instance.OnWest;
            @DUp.started += instance.OnDUp;
            @DUp.performed += instance.OnDUp;
            @DUp.canceled += instance.OnDUp;
            @DRight.started += instance.OnDRight;
            @DRight.performed += instance.OnDRight;
            @DRight.canceled += instance.OnDRight;
            @DDown.started += instance.OnDDown;
            @DDown.performed += instance.OnDDown;
            @DDown.canceled += instance.OnDDown;
            @DLeft.started += instance.OnDLeft;
            @DLeft.performed += instance.OnDLeft;
            @DLeft.canceled += instance.OnDLeft;
            @L1.started += instance.OnL1;
            @L1.performed += instance.OnL1;
            @L1.canceled += instance.OnL1;
            @L2.started += instance.OnL2;
            @L2.performed += instance.OnL2;
            @L2.canceled += instance.OnL2;
            @L3.started += instance.OnL3;
            @L3.performed += instance.OnL3;
            @L3.canceled += instance.OnL3;
            @R1.started += instance.OnR1;
            @R1.performed += instance.OnR1;
            @R1.canceled += instance.OnR1;
            @R2.started += instance.OnR2;
            @R2.performed += instance.OnR2;
            @R2.canceled += instance.OnR2;
            @R3.started += instance.OnR3;
            @R3.performed += instance.OnR3;
            @R3.canceled += instance.OnR3;
            @Start.started += instance.OnStart;
            @Start.performed += instance.OnStart;
            @Start.canceled += instance.OnStart;
            @Select.started += instance.OnSelect;
            @Select.performed += instance.OnSelect;
            @Select.canceled += instance.OnSelect;
            @LStick.started += instance.OnLStick;
            @LStick.performed += instance.OnLStick;
            @LStick.canceled += instance.OnLStick;
            @RStick.started += instance.OnRStick;
            @RStick.performed += instance.OnRStick;
            @RStick.canceled += instance.OnRStick;
            @RStickAltX.started += instance.OnRStickAltX;
            @RStickAltX.performed += instance.OnRStickAltX;
            @RStickAltX.canceled += instance.OnRStickAltX;
            @RStickAltY.started += instance.OnRStickAltY;
            @RStickAltY.performed += instance.OnRStickAltY;
            @RStickAltY.canceled += instance.OnRStickAltY;
        }

        private void UnregisterCallbacks(IMapActions instance)
        {
            @East.started -= instance.OnEast;
            @East.performed -= instance.OnEast;
            @East.canceled -= instance.OnEast;
            @North.started -= instance.OnNorth;
            @North.performed -= instance.OnNorth;
            @North.canceled -= instance.OnNorth;
            @South.started -= instance.OnSouth;
            @South.performed -= instance.OnSouth;
            @South.canceled -= instance.OnSouth;
            @West.started -= instance.OnWest;
            @West.performed -= instance.OnWest;
            @West.canceled -= instance.OnWest;
            @DUp.started -= instance.OnDUp;
            @DUp.performed -= instance.OnDUp;
            @DUp.canceled -= instance.OnDUp;
            @DRight.started -= instance.OnDRight;
            @DRight.performed -= instance.OnDRight;
            @DRight.canceled -= instance.OnDRight;
            @DDown.started -= instance.OnDDown;
            @DDown.performed -= instance.OnDDown;
            @DDown.canceled -= instance.OnDDown;
            @DLeft.started -= instance.OnDLeft;
            @DLeft.performed -= instance.OnDLeft;
            @DLeft.canceled -= instance.OnDLeft;
            @L1.started -= instance.OnL1;
            @L1.performed -= instance.OnL1;
            @L1.canceled -= instance.OnL1;
            @L2.started -= instance.OnL2;
            @L2.performed -= instance.OnL2;
            @L2.canceled -= instance.OnL2;
            @L3.started -= instance.OnL3;
            @L3.performed -= instance.OnL3;
            @L3.canceled -= instance.OnL3;
            @R1.started -= instance.OnR1;
            @R1.performed -= instance.OnR1;
            @R1.canceled -= instance.OnR1;
            @R2.started -= instance.OnR2;
            @R2.performed -= instance.OnR2;
            @R2.canceled -= instance.OnR2;
            @R3.started -= instance.OnR3;
            @R3.performed -= instance.OnR3;
            @R3.canceled -= instance.OnR3;
            @Start.started -= instance.OnStart;
            @Start.performed -= instance.OnStart;
            @Start.canceled -= instance.OnStart;
            @Select.started -= instance.OnSelect;
            @Select.performed -= instance.OnSelect;
            @Select.canceled -= instance.OnSelect;
            @LStick.started -= instance.OnLStick;
            @LStick.performed -= instance.OnLStick;
            @LStick.canceled -= instance.OnLStick;
            @RStick.started -= instance.OnRStick;
            @RStick.performed -= instance.OnRStick;
            @RStick.canceled -= instance.OnRStick;
            @RStickAltX.started -= instance.OnRStickAltX;
            @RStickAltX.performed -= instance.OnRStickAltX;
            @RStickAltX.canceled -= instance.OnRStickAltX;
            @RStickAltY.started -= instance.OnRStickAltY;
            @RStickAltY.performed -= instance.OnRStickAltY;
            @RStickAltY.canceled -= instance.OnRStickAltY;
        }

        public void RemoveCallbacks(IMapActions instance)
        {
            if (m_Wrapper.m_MapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMapActions instance)
        {
            foreach (var item in m_Wrapper.m_MapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MapActions @Map => new MapActions(this);
    public interface IMapActions
    {
        void OnEast(InputAction.CallbackContext context);
        void OnNorth(InputAction.CallbackContext context);
        void OnSouth(InputAction.CallbackContext context);
        void OnWest(InputAction.CallbackContext context);
        void OnDUp(InputAction.CallbackContext context);
        void OnDRight(InputAction.CallbackContext context);
        void OnDDown(InputAction.CallbackContext context);
        void OnDLeft(InputAction.CallbackContext context);
        void OnL1(InputAction.CallbackContext context);
        void OnL2(InputAction.CallbackContext context);
        void OnL3(InputAction.CallbackContext context);
        void OnR1(InputAction.CallbackContext context);
        void OnR2(InputAction.CallbackContext context);
        void OnR3(InputAction.CallbackContext context);
        void OnStart(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
        void OnLStick(InputAction.CallbackContext context);
        void OnRStick(InputAction.CallbackContext context);
        void OnRStickAltX(InputAction.CallbackContext context);
        void OnRStickAltY(InputAction.CallbackContext context);
    }
}
